import json
import os
import re
from datetime import datetime

from tqdm import tqdm


def parse_title(chat_text: str) -> str:
    m = re.search(r"^# (.+)", chat_text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    m = re.search(r"^## (?!SpecStory)(.+)", chat_text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    first_line = chat_text.splitlines()[0] if chat_text.splitlines() else ""
    m = re.search(r"^\*\*(.+?)\*\*$", first_line)
    if m:
        return m.group(1).strip()
    return "Untitled"


def extract_timestamp_from_name(name: str):
    if not name:
        return None

    m = re.search(r"(\d{4}\D+\d{2}\D+\d{2}\D+\d{2}\D+\d{2})", name)
    if m:
        normalized = re.sub(r"\D+", "-", m.group(1)).strip("-") + "-00"
        try:
            dt = datetime.strptime(normalized, "%Y-%m-%d-%H-%M-%S")
            return dt.strftime("%Y-%m-%d %H:%M:%S")
        except Exception:
            pass

    m = re.search(r"(\d{4}\D+\d{2}\D+\d{2})", name)
    if m:
        normalized = re.sub(r"\D+", "-", m.group(1)).strip("-")
        try:
            dt = datetime.strptime(normalized, "%Y-%m-%d")
            return dt.strftime("%Y-%m-%d %H:%M:%S")
        except Exception:
            return None
    return None


def extract_timestamp_from_text(chat_text: str):
    head = "\n".join(chat_text.splitlines()[:120])
    candidates = [
        r"\b\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}(?:\.\d+)?Z\b",
        r"\b\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}\b",
    ]
    for pat in candidates:
        m = re.search(pat, head)
        if not m:
            continue
        raw = m.group(0).replace(" ", "T")
        if raw.endswith("Z"):
            raw = raw[:-1] + "+00:00"
        try:
            dt = datetime.fromisoformat(raw)
            return dt.strftime("%Y-%m-%d %H:%M:%S")
        except Exception:
            continue
    return None


def clean_text(text: str) -> str:
    text = re.sub(r"\n{3,}", "\n\n", text.strip())
    return text


def normalize_role(role: str) -> str:
    r = role.strip().lower()
    if r.startswith("user"):
        return "User"
    if r.startswith("assistant") or r.startswith("agent"):
        return "Assistant"
    return "Assistant"


def detect_format(chat_text: str) -> str:
    if "WORK SESSION" in chat_text:
        return "work_session"
    if "Claude Code Session Log" in chat_text:
        return "claude_session"
    if "Generated by SpecStory" in chat_text or "_**User" in chat_text:
        return "specstory"
    return "unknown"


def parse_claude_session_messages(chat_text: str):
    pattern = re.compile(
        r"^### (User|Assistant|Agent)\s*\n(.*?)(?=^### (?:User|Assistant|Agent)\s*\n|\Z)",
        re.DOTALL | re.MULTILINE,
    )
    messages = []
    for match in pattern.finditer(chat_text):
        role = normalize_role(match.group(1))
        content = clean_text(match.group(2))
        if content:
            messages.append({"role": role, "content": content})
    return messages


def parse_specstory_messages(chat_text: str):
    pattern = re.compile(
        r"_\*\*((?:User|Assistant|Agent)[^\n]*?)\*\*_\n+(.*?)(?=(?:_\*\*(?:User|Assistant|Agent)[^\n]*?\*\*_\n+)|\Z)",
        re.DOTALL,
    )

    def is_inside_fence(text: str, pos: int) -> bool:
        # Odd number of fence markers before this position => inside a fenced block.
        return text[:pos].count("```") % 2 == 1

    messages = []
    for match in pattern.finditer(chat_text):
        if is_inside_fence(chat_text, match.start()):
            continue
        role = normalize_role(match.group(1))
        content = clean_text(re.sub(r"\n\n---\n\n", "\n", match.group(2)))
        if content:
            messages.append({"role": role, "content": content})
    return messages


def parse_work_session_messages(chat_text: str):
    tool_block_pattern = re.compile(
        r"^### ([^\n]+)\n(.*?)(?=^### [^\n]+\n|\Z)", re.DOTALL | re.MULTILINE
    )
    user_request_pattern = re.compile(
        r"\*\*User Request:\*\*\s*(.*?)(?=\n\*\*(?:Tool|Input|Result|Output|System Action):\*\*|\Z)",
        re.DOTALL,
    )
    system_action_pattern = re.compile(
        r"\*\*System Action:\*\*\s*(.*?)(?=\n\*\*(?:Tool|Input|Result|Output|User Request):\*\*|\Z)",
        re.DOTALL,
    )

    messages = []
    for match in tool_block_pattern.finditer(chat_text):
        heading = match.group(1).strip()
        body = match.group(2).strip()

        if heading.lower().startswith(("user", "assistant", "agent")):
            role = normalize_role(heading)
            content = clean_text(body)
            if content:
                messages.append({"role": role, "content": content})
            continue

        tool_name = heading.split(" - ", 1)[0].strip()

        user_parts = []
        user_match = user_request_pattern.search(body)
        if user_match:
            user_parts.append(clean_text(user_match.group(1)))
        action_match = system_action_pattern.search(body)
        if action_match:
            user_parts.append(clean_text(action_match.group(1)))

        if user_parts:
            user_content = "\n\n".join([p for p in user_parts if p])
            if user_content:
                messages.append(
                    {
                        "role": "User",
                        "content": user_content,
                        "metadata": {"tool": tool_name, "section": "request"},
                    }
                )

        assistant_body = body
        for m in [user_match, action_match]:
            if m:
                assistant_body = assistant_body.replace(m.group(0), "").strip()

        assistant_content = clean_text(assistant_body)
        if assistant_content:
            messages.append(
                {
                    "role": "Assistant",
                    "content": assistant_content,
                    "metadata": {"tool": tool_name, "section": "tool_result"},
                }
            )

    return messages


def parse_fallback_messages(chat_text: str):
    messages = parse_claude_session_messages(chat_text)
    if messages:
        return messages

    messages = parse_specstory_messages(chat_text)
    if messages:
        return messages

    m = re.search(r"\*\*User Request:\*\*\s*(.*)", chat_text, re.DOTALL)
    if m:
        return [{"role": "User", "content": clean_text(m.group(1))}]

    return [{"role": "Assistant", "content": clean_text(chat_text)}]


def parse_messages(chat_text: str, fmt: str):
    if fmt == "work_session":
        return parse_work_session_messages(chat_text)
    if fmt == "claude_session":
        return parse_claude_session_messages(chat_text)
    if fmt == "specstory":
        return parse_specstory_messages(chat_text)
    return parse_fallback_messages(chat_text)


def platform_from_format(fmt: str):
    if fmt == "work_session":
        return "WORK SESSION"
    if fmt == "claude_session":
        return "Claude Code 1"
    if fmt == "specstory":
        return "Claude Code 2"
    return "CLI Mixed"


def main():
    input_dir = "data/markdowns_cli"
    output_dir = "data/parsed_chats_simple_cli"
    os.makedirs(output_dir, exist_ok=True)

    with open("data/searches.json", encoding="utf-8") as f:
        searches = json.load(f)
    sha_to_name = {
        item.get("sha"): item.get("name") for item in searches if item.get("sha")
    }

    files = sorted([f for f in os.listdir(input_dir) if f.endswith(".md")])
    unknown_count = 0
    empty_count = 0

    for filename in tqdm(files):
        path = os.path.join(input_dir, filename)
        with open(path, encoding="utf-8") as f:
            chat_text = f.read()

        fmt = detect_format(chat_text)
        if fmt == "unknown":
            unknown_count += 1

        title = parse_title(chat_text)
        sha_key = filename[:-3]
        name = sha_to_name.get(sha_key)

        timestamp = extract_timestamp_from_text(chat_text)
        if not timestamp:
            timestamp = extract_timestamp_from_name(name)

        messages = parse_messages(chat_text, fmt)
        if not messages:
            messages = [{"role": "Assistant", "content": ""}]
            empty_count += 1

        parsed = {
            "title": title,
            "timestamp": timestamp,
            "platform": platform_from_format(fmt),
            "messages": messages,
        }

        out_path = os.path.join(output_dir, f"{filename}.json")
        with open(out_path, "w", encoding="utf-8") as wf:
            json.dump(parsed, wf, indent=2, ensure_ascii=False)

    print(f"Total CLI markdowns: {len(files)}")
    print(f"Total parsed simple chats (CLI): {len(os.listdir(output_dir))}")
    print(f"Unknown format count: {unknown_count}")
    print(f"Empty message fallback count: {empty_count}")


main()
